version: '3.4'
services:
  rest-conexa-challenger:
    image: felipebuilder/rest-conexa-challenger
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useTimezone=true&serverTimezone=UTC&useSSL=false
      SPRING.DATASOURCE.USERNAME: ${DB_USERNAME}
      SPRING.DATASOURCE.PASSWORD: ${DB_PASSWORD}
      SPRING.FLYWAY.URL: jdbc:mysql://${DB_HOST}:${DB_PORT}
      SPRING.DATA.REDIS.HOST: redis
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - redis
    networks:
      - conexa-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - conexa-network
networks:
  conexa-network:
    driver: bridge