cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:5000
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  application:
    name: rest-conexa-challenger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-conexa-challenger?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: admin123
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: rest-conexa-challenger
    user: root
    password: admin123
    locations: classpath:db/migration
springdoc:
  pathsToMatch: 
    - /auth/**
    - /api/v1/**
  swagger-ui:
    use-root-path: true