spring:
  application:
    name: rest-conexa-challenger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-conexa-challenger
    username: root
    password: admin123
#  datasource:
#    dbcp2:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/rest-conexa-challenger?useTimezone=true&serverTimezone=UTC
#      username: root
#      password: admin123
#  jpa:
#    hibernate:
#      ddl-auto: update ## in production use 'none'
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
#      show-sql: false